/**
 * Generated by ai
*/

import type { CoreStatisticPeriodData } from "./api";
import Random from "./random";

export default class Analyse {
    static period = (data: CoreStatisticPeriodData) => {
        const analyse: string[] = [];
        const { ac, submit } = data;

        // ========== 数据计算 ==========
        // 今日数据
        const todaySubmit = submit.today;
        const todayAc = ac.today;
        const todayAcRate = todaySubmit > 0 ? todayAc / todaySubmit : 0;

        // 本周数据
        const weekAc = ac.thisWeek;
        const weekSubmit = submit.thisWeek;
        const weekAcRate = weekSubmit > 0 ? weekAc / weekSubmit : 0;
        const lastWeekAc = ac.lastWeek;
        const weekTrend = weekAc - lastWeekAc;
        const weekTrendRate = lastWeekAc > 0 ? ((weekAc - lastWeekAc) / lastWeekAc) * 100 : 0;

        // 本月数据
        const monthAc = ac.thisMonth;
        const monthSubmit = submit.thisMonth;
        const monthAcRate = monthSubmit > 0 ? monthAc / monthSubmit : 0;
        const lastMonthAc = ac.lastMonth;
        const monthTrend = monthAc - lastMonthAc;
        const monthTrendRate = lastMonthAc > 0 ? ((monthAc - lastMonthAc) / lastMonthAc) * 100 : 0;

        // 今年数据
        const yearAc = ac.thisYear;
        const lastYearAc = ac.lastYear;
        const yearTrend = lastYearAc > 0 ? ((yearAc - lastYearAc) / lastYearAc) * 100 : 0;

        // 总量数据
        const totalAc = ac.total;
        const totalSubmit = submit.total;
        const overallAcRate = totalSubmit > 0 ? totalAc / totalSubmit : 0;

        // 当前时间信息（用于时间相关分析）
        const now = new Date();
        const currentHour = now.getHours();
        const currentDay = now.getDay(); // 0=周日, 1=周一, ..., 6=周六
        const currentDate = now.getDate();
        const currentMonth = now.getMonth() + 1;

        // ========== 今日表现分析 ==========
        if (todaySubmit > 0) {
            // 1. AC率分析 - 更加细化的分级和多样化的表达
            if (todaySubmit >= 5) { // 降低门槛到5题，让更多用户获得反馈
                if (todayAcRate > 0.9) {
                    analyse.push(Random.choice([
                        "🎯 今日 AC 率超过90%，解题精准度堪称完美！",
                        "🌟 今日 AC 率超过90%，简直是算法大师！",
                        "💫 今日 AC 率超过90%，精准打击，无一失手！",
                        "🏆 今日 AC 率超过90%，表现出色，继续保持！"
                    ]));
                } else if (todayAcRate > 0.8) {
                    analyse.push(Random.choice([
                        "🔥 今日 AC 率超过80%，解题精准度极高！",
                        "🚀 今日 AC 率超过80%，势如破竹！",
                        "✨ 今日 AC 率超过80%，闪耀全场！",
                        "👍 今日 AC 率超过80%，表现非常稳定！"
                    ]));
                } else if (todayAcRate > 0.7) {
                    analyse.push(Random.choice([
                        "✅ 今日 AC 率超过70%，解题准确度很不错！",
                        "📈 今日 AC 率超过70%，稳步提升中！",
                        "💪 今日 AC 率超过70%，继续保持这个势头！"
                    ]));
                } else if (todayAcRate > 0.6) {
                    analyse.push(Random.choice([
                        "👌 今日 AC 率良好，继续保持！",
                        "📊 今日 AC 率不错，稳中有进！",
                        "🎉 今日 AC 率超过60%，合格线以上，继续加油！"
                    ]));
                } else if (todayAcRate > 0.5) {
                    analyse.push(Random.choice([
                        "🤔 今日 AC 率刚过50%，还有提升空间哦",
                        "📝 今日 AC 率50%+，建议复盘错题寻找规律",
                        "🔍 今日 AC 率50%左右，可以尝试放慢节奏仔细思考"
                    ]));
                } else if (todayAcRate > 0.4) {
                    analyse.push(Random.choice([
                        "💡 今日 AC 率40%+，遇到了一些挑战，坚持就是胜利！",
                        "🧩 今日解题遇到些困难，这是成长的好机会",
                        "📚 建议回顾基础知识，夯实基础再战"
                    ]));
                } else if (todayAcRate > 0.3) {
                    analyse.push(Random.choice([
                        "🤨 今日 AC 率30%+，可能需要调整解题策略",
                        "🔄 遇到瓶颈时，换个角度思考问题",
                        "👥 可以和同学们交流一下解题思路"
                    ]));
                } else {
                    analyse.push(Random.choice([
                        "💪 今日遇到较大挑战，这正是突破自我的机会！",
                        "🧠 难题是进步的机会，尝试分析错误原因",
                        "📖 今日 AC 率偏低，是否需要调整解题策略？",
                        "🤝 今日 AC 率较低，是否遇到了难题？可以与同学们一起交流",
                        "🌱 每个大神都从低AC率开始，坚持就是胜利！"
                    ]));
                }
            }

            // 2. 提交量分析 - 更多分级和表达
            if (todaySubmit >= 50) {
                analyse.push(Random.choice([
                    "🚀🚀 今日提交量超过50，学习热情爆棚！",
                    "💥💥 今日高强度训练，进步速度肉眼可见！",
                    "🔥🔥 今日提交量惊人，算法能力飞速提升中！",
                    "🌟 今日提交量50+，这 dedication 值得称赞！"
                ]));
            } else if (todaySubmit >= 30) {
                analyse.push(Random.choice([
                    "🔥 今日提交量很高，学习热情满满！",
                    "💪 高强度训练，进步看得见！",
                    "📚 今日刷题量很大，积累就是力量！",
                    "⚡ 今日提交量30+，保持这个节奏！"
                ]));
            } else if (todaySubmit >= 20) {
                analyse.push(Random.choice([
                    "👍 今日提交量不错，保持了良好的练习节奏",
                    "📈 今日练习量充足，稳步提升中",
                    "🎯 今日提交量20+，有效的训练量"
                ]));
            } else if (todaySubmit >= 10) {
                analyse.push(Random.choice([
                    "👌 今日保持了良好的练习节奏",
                    "✅ 今日完成10+题目，每日进步一点点",
                    "📝 今日练习量达标，坚持就是胜利"
                ]));
            } else if (todaySubmit >= 5) {
                analyse.push(Random.choice([
                    "🌱 每日坚持，终将长成参天大树",
                    "✨ 今日完成5+题目，小步快跑",
                    "💫 积少成多，每天进步就是成功"
                ]));
            } else {
                analyse.push(Random.choice([
                    "🌅 今天已经开了一个好头，继续加油！",
                    "🎯 今天已经开始练习，继续保持！",
                    "📌 今天已经提交了题目，慢慢来比较快"
                ]));
            }

            // 3. 效率分析：AC率 vs 提交量的综合评估
            if (todaySubmit >= 10) {
                if (todayAcRate > 0.7 && todaySubmit >= 20) {
                    analyse.push(Random.choice([
                        "🏅 今日高提交量 + 高AC率，效率与质量并存！",
                        "🌟 今日既保持高产量又保证高质量，优秀！",
                        "💎 今日表现完美：量大且精准！"
                    ]));
                } else if (todayAcRate > 0.8 && todaySubmit < 10) {
                    analyse.push(Random.choice([
                        "🎯 今日虽然题量不多，但精度极高！",
                        "✨ 今日重质不重量，每道题都吃透了",
                        "🔍 今日精做少数题目，深度思考效果好"
                    ]));
                } else if (todayAcRate < 0.4 && todaySubmit >= 15) {
                    analyse.push(Random.choice([
                        "🔄 今日题量很大但AC率偏低，建议放慢节奏注重质量",
                        "📊 量多质不高时，可以尝试减少题量提高单题理解深度",
                        "💡 遇到瓶颈期，可以回归基础题目巩固信心"
                    ]));
                }
            }

            // 4. 时间段分析（基于当前时间）
            if (currentHour < 12) {
                analyse.push(Random.choice([
                    "🌅 清晨刷题，一日之计在于晨！",
                    "☀️ 早上就开启学习模式，自律的人最棒！",
                    "⏰ 早起的鸟儿有虫吃，早起的码农有题刷！"
                ]));
            } else if (currentHour < 18) {
                analyse.push(Random.choice([
                    "🌞 午后时光用来刷题，充实又高效！",
                    "📚 下午学习精力充沛，继续保持！",
                    "💼 学习之余坚持刷题，优秀！"
                ]));
            } else if (currentHour < 22) {
                analyse.push(Random.choice([
                    "🌙 晚上坚持刷题，超越同龄人！",
                    "🌟 晚间学习，安静的环境更适合思考",
                    "🦉 夜猫子模式开启，算法伴你入眠"
                ]));
            } else {
                analyse.push(Random.choice([
                    "🌌 深夜刷题，注意休息哦！",
                    "🌠 这么晚还在学习， dedication 满分！",
                    "💤 深夜算法，记得合理安排作息"
                ]));
            }
        } else {
            // 今天没有提交
            analyse.push(Random.choice([
                "🌱 今天还没开始练习，现在就开始吧！<a href='https://www.nowcoder.com/problem/tracker#/daily'>为您推荐</a>",
                "🎯 每天进步一点点，今天就从一道题开始。<a href='https://www.nowcoder.com/problem/tracker#/daily'>为您推荐</a>",
                "🚀 今日未检测到提交，立即开始你的算法之旅！<a href='https://www.nowcoder.com/problem/tracker#/daily'>为您推荐</a>",
                "📚 千里之行始于足下，从今天的第一题开始！<a href='https://www.nowcoder.com/problem/tracker#/daily'>为您推荐</a>"
            ]));
        }

        // ========== 本周分析 ==========
        const weekAnalysisDone = false; // 标记是否已添加周分析

        if (weekSubmit > 0) {
            // 1. 周趋势分析（不再限制周末）
            if (weekTrend > 10) {
                analyse.push(Random.choice([
                    `🚀 本周 AC 数比上周多 ${weekTrend} 题，进步神速！`,
                    `📈 本周进步明显，比上周多完成 ${weekTrend} 题！`,
                    `🌟 本周表现突出，AC数增长 ${weekTrend} 题！`,
                    weekTrendRate > 0 ? `🔥 本周 AC 数增长 ${weekTrendRate.toFixed(0)}%，飞速进步！` : `🔥 本周 AC 数增长 ${weekTrend} 题，太棒了！`
                ]));
            } else if (weekTrend > 5) {
                analyse.push(Random.choice([
                    `👍 本周 AC 数比上周多 ${weekTrend} 题，进步显著！`,
                    `📊 本周保持进步，多完成了 ${weekTrend} 题`,
                    `💪 本周稳步提升，比上周多 AC ${weekTrend} 题`
                ]));
            } else if (weekTrend > 0) {
                analyse.push(Random.choice([
                    `✅ 本周比上周多完成了 ${weekTrend} 题，继续加油！`,
                    `📝 本周有小幅进步，多 AC ${weekTrend} 题`,
                    `🌱 本周在进步，比上周多 ${weekTrend} 题`
                ]));
            } else if (weekTrend < -5) {
                analyse.push(Random.choice([
                    `🔄 本周活跃度有所下降，记得保持练习节奏哦`,
                    `💡 本周练习量减少，调整状态重新出发`,
                    `🤔 本周提交减少，是遇到困难了吗？可以找同学交流`
                ]));
            } else if (weekTrend < 0) {
                analyse.push(Random.choice([
                    `📉 本周练习量略有减少，下周争取补回来`,
                    `🔄 状态有小波动很正常，保持坚持最重要`,
                    `💪 本周稍有松懈，明天又是新的开始`
                ]));
            }

            // 2. 本周AC率分析
            if (weekSubmit >= 15) {
                if (weekAcRate > 0.8) {
                    analyse.push(Random.choice([
                        "🏅 本周解题准确率极高，状态爆棚！",
                        "💎 本周 AC 率超过80%，质量把控得很好！",
                        "🌟 本周高精度解题，优秀！"
                    ]));
                } else if (weekAcRate > 0.7) {
                    analyse.push(Random.choice([
                        "✅ 本周解题准确率很高，继续保持！",
                        "👍 本周 AC 率良好，稳定发挥",
                        "📈 本周解题质量不错，准确率达标"
                    ]));
                } else if (weekAcRate > 0.6) {
                    analyse.push(Random.choice([
                        "👌 本周 AC 率合格，还有提升空间",
                        "📊 本周准确率达标，可以尝试挑战更高精度",
                        "🎯 本周命中率60%+，继续优化"
                    ]));
                } else if (weekAcRate < 0.4) {
                    analyse.push(Random.choice([
                        "🧩 本周遇到较多挑战，建议复盘错题，总结规律",
                        "📚 本周准确率偏低，可以回归基础题目",
                        "🔍 本周解题遇到困难，分析错因是关键"
                    ]));
                } else if (weekAcRate < 0.5) {
                    analyse.push(Random.choice([
                        "💡 本周准确率有提升空间，注重理解而非速度",
                        "🤔 本周 AC 率50%以下，建议放慢节奏保证质量",
                        "🔄 调整策略：先保证正确率，再提升速度"
                    ]));
                }
            }

            // 3. 周提交量分析
            if (weekSubmit >= 100) {
                analyse.push(Random.choice([
                    "🔥🔥 本周提交量破百，简直是刷题机器！",
                    "🚀🚀 本周高强度训练，进步肉眼可见！",
                    "💥💥 本周提交量100+， dedication 惊人！"
                ]));
            } else if (weekSubmit >= 50) {
                analyse.push(Random.choice([
                    "🔥 本周提交量50+，学习热情高涨！",
                    "💪 本周训练量充足，积累效果显著",
                    "📚 本周刷题量很大，坚持就是胜利"
                ]));
            } else if (weekSubmit >= 30) {
                analyse.push(Random.choice([
                    "👍 本周保持了良好的练习频率",
                    "✅ 本周训练量达标，稳步前进",
                    "📈 本周提交量30+，持续进步中"
                ]));
            }

            // 4. 周末特别分析（如果是周末）
            if (currentDay === 0 || currentDay === 6) {
                if (weekSubmit >= 20) {
                    analyse.push(Random.choice([
                        "🎉 周末还在坚持刷题，超越99%的人！",
                        "🌟 利用周末时间提升自己，优秀！",
                        "💫 周末充电，工作日更有信心"
                    ]));
                }
            }
        }

        // ========== 月度分析 ==========
        if (monthSubmit > 0) {
            // 月度进步情况（不再限制20号以后）
            if (monthTrend > 30) {
                analyse.push(Random.choice([
                    `🚀🚀 本月 AC 数比上月大幅增加 ${monthTrend} 题，太棒了！`,
                    `💥💥 本月进步惊人，多完成了 ${monthTrend} 题！`,
                    `🌟🌟 本月表现卓越，AC数增长 ${monthTrend} 题！`,
                    monthTrendRate > 0 ? `🔥🔥 本月 AC 数增长 ${monthTrendRate.toFixed(0)}%，突飞猛进！` : `🔥🔥 本月 AC 数增长 ${monthTrend} 题，太强了！`
                ]));
            } else if (monthTrend > 15) {
                analyse.push(Random.choice([
                    `🔥 本月 AC 数比上月增加 ${monthTrend} 题，显著进步！`,
                    `📈 本月保持良好势头，多完成了 ${monthTrend} 题`,
                    `💪 本月稳步前进，比上月多 AC ${monthTrend} 题`
                ]));
            } else if (monthTrend > 5) {
                analyse.push(Random.choice([
                    `👍 本月比上月多完成了 ${monthTrend} 题，继续努力！`,
                    `✅ 本月有小幅进步，多 AC ${monthTrend} 题`,
                    `🌱 本月在进步中，比上月多 ${monthTrend} 题`
                ]));
            }

            // 月度AC率分析
            if (monthSubmit >= 50) {
                if (monthAcRate > 0.75) {
                    analyse.push(Random.choice([
                        "🏅 本月解题准确率很高，质量把控完美！",
                        "💎 本月保持高精度解题，优秀习惯已养成",
                        "🌟 本月 AC 率75%+，稳定且高效"
                    ]));
                } else if (monthAcRate > 0.65) {
                    analyse.push(Random.choice([
                        "✅ 本月解题准确率良好，继续保持",
                        "👍 本月 AC 率达标，表现稳定",
                        "📊 本月解题质量不错，准确率在合理范围"
                    ]));
                } else if (monthAcRate < 0.45) {
                    analyse.push(Random.choice([
                        "💡 本月准确率有较大提升空间，建议系统复习",
                        "🔄 本月遇到挑战，下个月调整策略重新出发",
                        "📚 本月准确率偏低，回归基础可能有所帮助"
                    ]));
                }
            }

            // 月度提交量分析
            if (monthSubmit >= 200) {
                analyse.push(Random.choice([
                    "🔥🔥🔥 本月提交量破200，简直是算法狂人！",
                    "🚀🚀🚀 本月高强度训练，实力暴涨！",
                    "💥💥💥 本月提交量200+， dedication 爆表！"
                ]));
            } else if (monthSubmit >= 100) {
                analyse.push(Random.choice([
                    "🔥🔥 本月提交量破百，努力程度满分！",
                    "💪💪 本月训练量惊人，进步看得见",
                    "🌟🌟 本月提交量100+，坚持的力量"
                ]));
            } else if (monthSubmit >= 50) {
                analyse.push(Random.choice([
                    "🔥 本月提交量50+，保持了良好的学习节奏",
                    "📈 本月训练量充足，积累效果明显",
                    "✅ 本月提交量达标，持续进步中"
                ]));
            }
        }

        // ========== 年度分析 ==========
        if (yearAc > 0 && lastYearAc > 0) {
            // 不再限制10月以后，全年都可对比
            if (yearTrend > 100) {
                analyse.push(Random.choice([
                    `🚀🚀🚀 今年比去年进步 ${yearTrend.toFixed(0)}%，成长速度惊人！`,
                    `💥💥💥 今年进步 ${yearTrend.toFixed(0)}%，突飞猛进！`,
                    `🌟🌟🌟 今年成长 ${yearTrend.toFixed(0)}%，质的飞跃！`
                ]));
            } else if (yearTrend > 50) {
                analyse.push(Random.choice([
                    `🚀🚀 今年比去年进步 ${yearTrend.toFixed(0)}%，成长飞速！`,
                    `🔥🔥 今年进步 ${yearTrend.toFixed(0)}%，显著提升！`,
                    `💪💪 今年成长 ${yearTrend.toFixed(0)}%，越来越强！`
                ]));
            } else if (yearTrend > 20) {
                analyse.push(Random.choice([
                    `🚀 今年保持稳定成长，比去年进步 ${yearTrend.toFixed(0)}%`,
                    `📈 今年进步 ${yearTrend.toFixed(0)}%，稳步前进`,
                    `👍 今年比去年提升 ${yearTrend.toFixed(0)}%，继续加油`
                ]));
            } else if (yearTrend > 0) {
                analyse.push(Random.choice([
                    `✅ 今年比去年进步 ${yearTrend.toFixed(0)}%，微小进步也是进步`,
                    `🌱 今年有小幅成长，提升 ${yearTrend.toFixed(0)}%`,
                    `📝 今年在进步中，比去年好 ${yearTrend.toFixed(0)}%`
                ]));
            } else if (yearTrend < 0) {
                analyse.push(Random.choice([
                    `🔄 今年进度稍慢，调整状态重新出发`,
                    `💡 每年节奏不同，找到适合自己的学习频率`,
                    `🤔 今年对比去年有下降，分析原因调整策略`
                ]));
            }
        }

        // ========== 总体数据与里程碑 ==========
        // 1. 总体AC率分析
        if (totalSubmit >= 50) {
            if (overallAcRate > 0.8) {
                analyse.push(Random.choice([
                    "🏆🏆 总体 AC 率超过80%，算法功底深厚！",
                    "💎💎 长期保持高精度解题，大师风范！",
                    "🌟🌟 总体 AC 率80%+，质量与坚持的完美结合"
                ]));
            } else if (overallAcRate > 0.7) {
                analyse.push(Random.choice([
                    "🏆 总体 AC 率超过70%，表现非常优秀！",
                    "👍 长期保持良好准确率，习惯养成成功",
                    "✅ 总体 AC 率70%+，稳定发挥的证明"
                ]));
            } else if (overallAcRate > 0.6) {
                analyse.push(Random.choice([
                    "✅ 总体 AC 率合格，有扎实的基础",
                    "📊 总体准确率达标，继续保持",
                    "👌 总体 AC 率60%+，表现不错"
                ]));
            } else if (overallAcRate < 0.4) {
                analyse.push(Random.choice([
                    "💡 总体 AC 率有提升空间，建议系统复习基础",
                    "🔄 准确率偏低可能是基础不牢，建议夯实基础",
                    "📚 总体 AC 率40%以下，回归基础题目可能有益"
                ]));
            }
        }

        // 2. 里程碑祝贺 - 更丰富的里程碑体系
        if (totalAc >= 2000 && totalAc <= 2100) {
            analyse.push(Random.choice([
                "🎉🎉🎉 恭喜达成两千题成就！算法宗师之路！",
                "🌟🌟🌟 两千题里程碑！坚持与汗水的结晶！",
                "🏆🏆🏆 两千题达成，已是算法领域的佼佼者！"
            ]));
        } else if (totalAc >= 1500 && totalAc <= 1600) {
            analyse.push(Random.choice([
                "🎉🎉 一千五百题成就！算法大师之路！",
                "🌟🌟 1500题里程碑，距离宗师仅一步之遥！",
                "🏆🏆 1500题达成，实力非凡！"
            ]));
        } else if (totalAc >= 1000 && totalAc <= 1100) {
            analyse.push(Random.choice([
                "🎉🎉 恭喜达成千题成就！这是坚持的最好证明",
                "🌟🌟 千题里程碑，算法高手认证！",
                "🏆🏆 突破1000题大关，进入新的境界！"
            ]));
        } else if (totalAc >= 800 && totalAc <= 850) {
            analyse.push(Random.choice([
                "🎉 800题成就达成，距离千题仅一步之遥！",
                "🌟 800题里程碑，坚持的力量！",
                "👍 800题突破，越来越强！"
            ]));
        } else if (totalAc >= 500 && totalAc <= 550) {
            analyse.push(Random.choice([
                "🎉 已突破500题大关，距离高手更进一步！",
                "🌟 500题里程碑，算法进阶之路！",
                "🔥 500题达成，实力显著提升！"
            ]));
        } else if (totalAc >= 300 && totalAc <= 350) {
            analyse.push(Random.choice([
                "✅ 300题成就达成，算法基础已牢固！",
                "📈 突破300题，进入中级阶段！",
                "💪 300题里程碑，继续前进！"
            ]));
        } else if (totalAc >= 200 && totalAc <= 250) {
            analyse.push(Random.choice([
                "👍 200题成就达成，算法学习步入正轨！",
                "📊 200题里程碑，坚持初见成效！",
                "🎯 突破200题，渐入佳境！"
            ]));
        } else if (totalAc >= 100 && totalAc <= 150) {
            analyse.push(Random.choice([
                "🎉 百题成就达成，恭喜入门算法！",
                "🌟 100题里程碑，算法之旅正式启航！",
                "🔥 突破100题，从新手到熟手的转变！"
            ]));
        } else if (totalAc >= 50 && totalAc <= 70) {
            analyse.push(Random.choice([
                "✅ 50题成就达成，算法学习初见成效！",
                "📝 50题里程碑，坚持就是胜利！",
                "🌱 突破50题，基础正在夯实！"
            ]));
        } else if (totalAc >= 20 && totalAc <= 40) {
            analyse.push(Random.choice([
                "👌 20题成就达成，学习之旅已开启！",
                "🚀 20题里程碑，好的开始是成功的一半！",
                "💫 突破20题，继续保持！"
            ]));
        } else if (totalAc >= 10 && totalAc <= 15) {
            analyse.push(Random.choice([
                "🌅 10题成就达成，算法学习迈出第一步！",
                "🎯 10题里程碑，坚持每天进步一点点",
                "✨ 突破10题，学习习惯正在养成"
            ]));
        }

        // 3. 提交总量里程碑
        if (totalSubmit >= 2000) {
            analyse.push(Random.choice([
                "📚📚📚 总提交量破2000，练习量惊人！",
                "💥💥💥 2000+次提交，汗水铸就实力！",
                "🔥🔥🔥 总提交量2000+， dedication 的证明！"
            ]));
        } else if (totalSubmit >= 1000) {
            analyse.push(Random.choice([
                "📚📚 总提交量破千，付出终有回报！",
                "💥💥 1000+次提交，努力看得见！",
                "🔥🔥 总提交量1000+，坚持的力量！"
            ]));
        } else if (totalSubmit >= 500) {
            analyse.push(Random.choice([
                "📚 总提交量500+，积累效果显著！",
                "💪 500+次尝试，经验在增长！",
                "✅ 总提交量达标，练习量充足"
            ]));
        }

        // 4. 效率与坚持度分析
        if (totalSubmit >= 100) {
            const efficiency = totalAc / totalSubmit; // 就是overallAcRate

            if (efficiency > 0.75 && totalAc >= 300) {
                analyse.push(Random.choice([
                    "💎💎 高准确率 + 大量练习 = 算法高手！",
                    "🏅 质量与数量的完美平衡，优秀！",
                    "🌟 既坚持练习又保证质量，成功之道"
                ]));
            }

            // 计算日均题量（近似）
            const daysSinceStart = 365; // 简化假设一年
            const dailyAverage = totalAc / daysSinceStart;

            if (dailyAverage >= 2) {
                analyse.push(Random.choice([
                    "📅 日均2题+，持续学习习惯优秀！",
                    "🗓️ 保持每日练习，时间会给你答案",
                    "⏰ 日均刷题量可观，坚持的力量"
                ]));
            }
        }

        // ========== 个性化建议 ==========
        // 基于综合表现给出建议
        if (analyse.length > 0) {
            // 根据近期表现给出建议
            const recentActivity = todaySubmit > 0 || weekSubmit > 10;
            const goodAccuracy = todayAcRate > 0.7 || weekAcRate > 0.65;

            if (recentActivity && goodAccuracy) {
                analyse.push(Random.choice([
                    "💡 建议：保持当前节奏，适当挑战更难的题目",
                    "🎯 下一步：可以尝试竞赛题目或专题训练",
                    "🚀 进阶：考虑参加算法竞赛检验实力"
                ]));
            } else if (recentActivity && !goodAccuracy) {
                analyse.push(Random.choice([
                    "💡 建议：放慢节奏，注重题目理解和错题分析",
                    "🎯 下一步：建立错题本，定期复习错题",
                    "📚 行动：回归基础题目，巩固算法思想"
                ]));
            } else if (!recentActivity && totalAc > 100) {
                analyse.push(Random.choice([
                    "💡 建议：恢复每日练习习惯，哪怕只是一道题",
                    "🎯 下一步：设定小目标，比如每周10题",
                    "🔄 行动：从简单题目开始，重拾刷题节奏"
                ]));
            }
        }

        // 牛客网题目推荐
        // 根据表现推荐不同难度的题目
        // if (totalAc < 50) {
        //     analyse.push("🔗 推荐：<a href=''>新手入门题目集</a>");
        // } else if (totalAc < 200) {
        //     analyse.push("🔗 推荐：<a href=''>中级进阶题目集</a>");
        // } else if (todayAcRate > 0.7) {
        //     analyse.push("🔗 推荐：<a href=''>挑战高难度题目</a>");
        // } else if (todayAcRate < 0.4) {
        //     analyse.push("🔗 推荐：<a href=''>基础巩固题目集</a>");
        // } else {
            analyse.push("🔗 推荐：<a href='https://www.nowcoder.com/problem/tracker#/daily'>每日一题保持手感</a>");
        // }

        return analyse;
    }
}